- hosts: all
  tasks:
    - name: Install needed packages
      package:
        name: ['intltool', 'libxslt', 'libxml2']
        state: present
      become: yes
    - name: Validate comps files
      ansible.builtin.command:
        chdir: "{{ zuul.project.src_dir }}"
        cmd: ci/validate-comps
